### PR TITLE
Issue #205 - Update to callback - Inquirer interface requires Promise

### PR DESCRIPTION
**Pull request by zacharytelschow**
@jimthedev: I realize the irony of not using one of your commit adapters to submit a pull request, but I didn't see contribution guidelines in your README :smile: I have tested this change on my local and it works. Please let me know if there are any further changes you'd like to see.

### CODE REVIEW

**Comment by zacharytelschow** [comment]
[Link to issue](https://github.com/commitizen/cz-cli/issues/205) since it's actually in [another repo](https://github.com/commitizen/cz-cli).

**Comment by jmfrancois** [comment]
Please @jimthedev merge this.
This plugin just doesn't work at the moment, I have try the change and it works.

update: oh the tests... Could you @zacharytelschow update the tests ?

**Comment by jimthedev** [comment]
@janecakemaster originally wrote the tests, I wonder if she'd be willing to help. Also we need to get a working travis config.

**Comment by janecakemaster** [comment]
@jimthedev which test are we talking about? sry it's been a while since I've touched this 😁

**Comment by jimthedev** [comment]
@janecakemaster haha no worries. Basically @zacharytelschow made some changes in his fork that break the tests you previously wrote. He is afk for right now but if you run the following you'll see the tests that are failing:

```
git clone https://github.com/zacharytelschow/cz-jira-smart-commit.git
cd cz-jira-smart-commit
git checkout Issue205
npm install
npm run test
```

**Comment by LinusU** [comment]
I think that we should add inquirer as a dependency and require it ourselves, as discussed here: https://github.com/commitizen/cz-cli/issues/249

This will prevent this from happening again :)

If we merge this as is, it will break for people using an older cz-cli (which they presumable are using since updating breaks...)

**Comment by jmfrancois** [comment]
But do not merge it means unusable for every new comer that just install last cz-cli (my case).

**Comment by jimthedev** [comment]
Yes, this would be a breaking change. We'd go to 2.0.

## 

Jim ForCy

**Comment by janecakemaster** [comment]
@zacharytelschow `sinon.spy` doesn't support promises. you'll have to look into a test spy/stub utility that lets you stub a promise-y function. maybe https://www.npmjs.com/package/sinon-as-promised might work?

**Comment by LinusU** [comment]
This will not be a breaking change if we require and use our own version of inquirer

**Comment by bgannonPL** [comment]
I appreciate that you all care about fixing this the right way. But in the meantime, people depend on this package and it has been unusable for some time with the current version of commitizen.

**Comment by LinusU** [comment]
@bgannonPL the correct fix is here 🎉 -> #5

**Comment by LinusU** [comment]
Resolved with #5

**Pull request closed without merging**
