### PR TITLE
Fix for Commitzen 2.9.6 + Global Installer

### PR DESCRIPTION
**Pull request by pgoodjohn**
Edited `index.js` to work with Commitzen 2.9.6.

Also added a `.sh` script to install `cz-jira-smart-commit` globally and set it as default Commitzen configuration.

### CODE REVIEW

**Comment by jimthedev** [comment]
I just fixed the tests and cut a release. 3.0.0 should be on npm. If you could take a look to make sure this works I'd appreciate it. I don't really use this adapter so any help is appreciated!

**Comment by pgoodjohn** [comment]
3.0.0 is live and working perfectly! Thanks a lot.
I'd be more than happy to keep an eye out for any future problems as it has become a daily tool for us, it's no problem for us to fix any problem that might arise in the future!

**Comment by jimthedev** [comment]
Sounds good! Added you to github group. If you send me your npm details I can add you there too.

**Comment by pgoodjohn** [comment]
Username on NPM is the same as here [@pgoodjohn](https://www.npmjs.com/~pgoodjohn)

**Pull request merged**
